### ISSUE TITLE
Smartflow类库程序改造成restful API

### ISSUE THREAD

**Issue by flybalance** [chengderen/Smartflow-Sharp#5]
想请教下作者，当时是基于怎样的考虑来决定使用dll引入的方式调用Smartflow工作流服务，而不是使用restful API的方式提供服务，后期是否有改造成restful API的计划

**Comment by chengderen** [comment]
目前WebApi已经接近改造完成。后续会陆续将源代码公开。

**Comment by chengderen** [comment]
已经完成，发布到上去。也有在线示例，不过服务器有一点垃圾，将就着看吧。
http://www.smartflow-sharp.com/Smartflow.Web.Mvc/login.html
